apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fbc-pipeline
  labels:
    build.appstudio.redhat.com/pipeline: build
spec:
  description: |
    This is a trimmed pipeline that ONLY executes the validate-fbc task on a pre-existing image.
  params:
  - description: The URL of the image to be validated.
    name: IMAGE_URL
    type: string
  - description: The digest of the image to be validated.
    name: IMAGE_DIGEST
    type: string
  - default: "false"
    description: Skip checks against the image. Set to "false" to run the validation.
    name: skip-checks
    type: string
  tasks:
  - name: validate-fbc
    params:
    - name: IMAGE_URL
      value: 'quay.io/redhat-user-workloads/cnv-fbc-tenant/v418-cnv-fbc:0a8b1ca9249061562d4e62ab60a9ea9d7d2cafa0'
    - name: IMAGE_DIGEST
      value: 'sha256:2bb7c4cb4a3868c1abe1e1aff1eaf2cf6db4246cf2082c033262549d920ecf0e'
    taskRef:
        params:
        - name: url
          value: https://github.com/ashwinifork/build-definitions.git
        - name: revision
          value: validate_fbc_directory_structure
        - name: pathInRepo
          value: task/validate-fbc/0.1/validate-fbc.yaml
        resolver: git

    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"